export const content = {
    en: {
      home: "Home",
      product: "Products",
      brands: "Brands",
      categories: "Categories",
      catalogs: "Catalogs",
      blog: "Blog",
      contact: "Contact",
      showmore: "Show more",
      ourPartners: "Our partners",
      gallery: "Gallery",
      new: "New arrival",
      buynow: "BUY NOW",
      contactheading: "Get In Touch With Us",
      contactinfo: "For More Information About Our Product & Services. Please Feel Free To Drop Us An Email. Our Staff Always Be There To Help You Out. Do Not Hesitate!",
      filter: "Filter",
      show: "Show",
      search: "Search",
      next: "Next",
      previous: "Previous",
      relatedproducts: "Related Products",
      submit: "Submit",
      address: "Address",
      phone: "Phone",
      workingtime: "Working time",
      name: "Your Name",
      email: "Email Address",
      subject: "Subject",
      message: "Message",
      recentposts: "Recent Posts",
      powered: "Powered by 4DX",
      reserved: "2023 EPLSM. All rights reserved",
      specification: "Specification",
      description: "Description",
      additionalinformation: "Additional Information",
      noinfo: "No information added!",
      elevatedcraftsmanship: "Elevated Craftsmanship",
      precisionengineering: "Precision Engineering",
      extendedsecurity: "Extended Security",
      warrantyconfidence: "Warranty Confidence",
      tailoredassistance: "Tailored Assistance",
      personalizedassistance: "Personalized assistance",
      unwaveringsupport: "Unwavering Support",
      reliableassistance: "Reliable Assistance",
    },
    ru: {
      home: "Главная страница",
      product: "Продукция",
      brands: "Бренды",
      categories: "Категории",
      catalogs: "Каталоги",
      blog: "Блог",
      contact: "Контакт",
      showmore: "Показать больше",
      ourPartners: "Наши партнеры",
      gallery: "Галерея",
      new: "Новое поступление",
      buynow: "КУПИТЬ СЕЙЧАС",
      contactheading: "Свяжитесь с Нами",
      contactinfo: "Для получения дополнительной информации о наших продуктах и услугах. Пожалуйста, не стесняйтесь, напишите нам по электронной почте. Наши сотрудники всегда готовы помочь вам. Не стесняйтесь!",
      filter: "Фильтр",
      show: "Показывать",
      search: "Поиск",
      next: "Следующий",
      previous: "Предыдущий",
      relatedproducts: "Сопутствующие Товары",
      submit: "Отправить",
      address: "Адрес",
      phone: "Телефон",
      workingtime: "Рабочее время",
      name: "Ваше имя",
      email: "Адрес электронной почты",
      subject: "Тема",
      message: "Сообщение",
      recentposts: "Недавние Посты",
      powered: "При поддержке 4DX",
      reserved: "2023 EPLSM. Все права защищены",
      specification: "Спесификации",
      description: "Описание",
      additionalinformation: "Дополнительные информации",
      noinfo: "Информация не добавлена!",
      elevatedcraftsmanship: "Повышенное Mастерство",
      precisionengineering: "Точное Mашиностроение",
      extendedsecurity: "Расширенная Безопасность",
      warrantyconfidence: "Гарантия Уверенность",
      tailoredassistance: "Индивидуальная Помощь",
      personalizedassistance: "Персонализированная Помощь",
      unwaveringsupport: "Непоколебимая Поддержка",
      reliableassistance: "Надежная Помощь",
    },
    uz: {
      home: "Bosh sahifa",
      product: "Mahsulotlar",
      brands: "Brendlar",
      categories: "Toifalar",
      catalogs: "Kataloglar",
      blog: "Blog",
      contact: "Kontakt",
      showmore: "Ko'proq ko'rsatish",
      ourPartners: "Bizning hamkorlar",
      gallery: "Galereya",
      new: "Yangi kelgan",
      buynow: "HOZIR XARID QILISH",
      contactheading: "Biz Bilan Bog'laning",
      contactinfo: "Mahsulotlarimiz va xizmatlarimiz haqida ko'proq ma'lumot olish uchun. Iltimos, bizga elektron pochta xabarini yuboring. Bizning xodimlarimiz sizga yordam berish uchun doimo u erda bo'lishadi. Ikkilanmang!",
      filter: "Filtr",
      show: "Ko'rsatish",
      search: "Qidirmoq",
      next: "Keyingisi",
      previous: "Oldingi",
      relatedproducts: "Tegishli mahsulotlar",
      submit: "Yuborish",
      address: "Manzil",
      phone: "Telefon",
      workingtime: "Ish vaqti",
      name: "Ismingiz",
      email: "E-pochta manzili",
      subject: "Mavzu",
      message: "Xabar",
      recentposts: "Oxirgi xabarlar",
      powered: "4DX tomonidan qo'llab quvvatlandi",
      reserved: "2023 EPLSM. Barcha huquqlar himoyalangan",
      specification: "Spetifikatsiyalar",
      description: "Tavsifi",
      additionalinformation: "Qo'shimcha ma'lumotlar",
      noinfo: "Ma'lumot qo'shilmagan!",
      elevatedcraftsmanship: "Yuksak Hunarmandchilik",
      precisionengineering: "Aniq Muhandislik",
      extendedsecurity: "Kengaytirilgan Xavfsizlik",
      warrantyconfidence: "Kafolat Ishonch",
      tailoredassistance: "Moslashtirilgan Yordam",
      personalizedassistance: "Shaxsiy Yordam",
      unwaveringsupport: "Cheksiz qo'llab-quvvatlash",
      reliableassistance: "Ishonchli Yordam",
    },
  };